import type { Locale } from '../locale';
export interface LandingCopy {
    skip: string;
    home: string;
    navigation: string;
    studio: string;
    features: string;
    workflow: string;
    start: string;
    eyebrow: string;
    title: readonly [string, string];
    statement: readonly [string, string];
    introduction: string;
    newProject: string;
    example: string;
    accountNote: string;
    resume: string;
    preparingExample: string;
    preparingProject: string;
    cancel: string;
    heroNote: string;
    seeStudio: string;
    editorLabel: string;
    editorAlt: string;
    editorCaption: string;
    editorNote: string;
    detailEyebrow: string;
    detailTitle: readonly [string, string];
    detailRhythm: readonly [string, string, string];
    detailDescription: string;
    detailLink: string;
    studyTitle: string;
    studyLabel: string;
    studyDescription: string;
    studyFrom: string;
    studyTo: string;
    studyCursor: string;
    studyTimings: string;
    studyPosition: string;
    studyOpacity: string;
    studyPositionDuration: string;
    studyOpacityDuration: string;
    studyControl: string;
    studyRange: string;
    studyTotal: string;
    seconds: string;
    workflowEyebrow: string;
    workflowTitle: readonly [string, string];
    workflowIntroduction: readonly [string, string];
    sharingTitle: string;
    sharingDescription: string;
    sharingAside: readonly [string, string];
    aiTitle: string;
    aiBeforeMention: string;
    aiAfterMention: string;
    aiExampleLabel: string;
    aiExampleEyebrow: string;
    aiExample: string;
    aiReview: string;
    mediaTitle: string;
    mediaDescription: string;
    mediaAside: readonly [string, string];
    closingEyebrow: string;
    closingTitle: readonly [string, string];
    closingAction: string;
    closingNote: string;
    backToTop: string;
    footerNote: string;
}
export declare const LANDING_COPY: Record<Locale, LandingCopy>;
