// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { visibleAnimation, visibleAnimations } from "../../../../_build/js/release/build/boundary/boundary.js";
