// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { handleMedia } from "../../../_build/js/release/build/node_assets/node_assets.js";
