// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { resolveLocale } from "../../../_build/js/release/build/site_boundary/site_boundary.js";
