import type { ObjectKind, AnimationKind, Point, Bezier, SceneObject, ObjectState, Composition, AnimationTiming, AnimationTrack, Transition, Scene, Project, Segment } from "./scene-types";
export type { ObjectKind, AnimationKind, Point, Bezier, SceneObject, ObjectState, Composition, AnimationTiming, AnimationTrack, Transition, Scene, Project, Segment } from "./scene-types";
import type { ImageAsset } from './images';
import type { AudioTrack, MediaAsset, MediaPlayback } from './media';
import type { Easing, PresetEasing } from './easing';
export { DEFAULT_CUSTOM_EASING, isValidEasing, easingsEqual, type PresetEasing, type CubicBezierEasing, type Easing } from './easing';
export declare const PROPERTY_CHANNELS: readonly ['position', 'opacity', 'size', 'rotation', 'fill', 'stroke', 'strokeWidth', 'fontSize', 'cornerRadius', 'path', 'reveal'];
export type PropertyChannel = typeof PROPERTY_CHANNELS[number];
export type PropertyTimingKey = `${PropertyChannel}Timing`;
export declare const PROPERTY_CHANNEL_LABELS: Record<PropertyChannel, string>;
export declare const propertyTimingKey: (channel: PropertyChannel) => PropertyTimingKey;
export type Selection = {
    kind: 'composition' | 'transition';
    id: string;
};
export declare const COLORS: string[];
export declare const KINDS: Record<ObjectKind, string>;
export declare const EASINGS: Record<PresetEasing, string>;
export declare const ANIMATIONS: Record<AnimationKind, string>;
export declare const newId: (prefix?: string) => string;
export declare const defaultState: (kind: ObjectKind, overrides?: Partial<ObjectState>) => ObjectState;
export declare const defaultTrack: (objectId: string, overrides?: Partial<AnimationTrack>) => AnimationTrack;
export declare const getPropertyTiming: (track: AnimationTrack, channel: PropertyChannel) => AnimationTiming;
export declare const hasPropertyTiming: (track: AnimationTrack, channel: PropertyChannel) => boolean;
export declare const resolveTrack: (track: AnimationTrack | undefined, objectId: string, duration: number) => AnimationTrack;
export declare const implicitTracks: (objectIds: string[], duration: number) => Record<string, AnimationTrack>;
export declare const trackTimingEnd: (track: AnimationTrack, includeBase?: boolean) => number;
export declare const validateAnimationTiming: (timing: AnimationTiming, duration: number) => void;
export declare const validateAnimationTrack: (track: AnimationTrack, duration: number) => void;
export declare const sceneSegments: (scene: Scene) => Segment[];
export declare const sceneDuration: (scene: Scene) => number;
export declare const orderedObjects: (scene: Scene) => SceneObject[];
export declare const stateFor: (scene: Scene, compositionId: string, objectId: string) => ObjectState | undefined;
export declare const clamp: (value: number, min: number, max: number) => number;
export declare const ms: (value: number) => string;
