// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { prefersMarkdown, publicPagePlan, fetchPublicPage } from "../../../_build/js/release/build/http_runtime/http_runtime.js";
