// Generated by scripts/generate-adapters.py from moonbit/scene/model.mbt and kinds.mbt.
export type ObjectKind = 'circle' | 'rectangle' | 'text' | 'equation' | 'path' | 'arrow' | 'numberline' | 'image' | 'video';
export type AnimationKind = 'move' | 'write' | 'fade' | 'grow' | 'none';
export type Effect = 'none' | 'glow';
export type PresetEasing = 'linear' | 'easeInOut' | 'easeIn' | 'easeOut';
export interface CubicBezierEasing { type: 'cubicBezier'; x1: number; y1: number; x2: number; y2: number }
export type Easing = PresetEasing | CubicBezierEasing;
export interface Point {
  x: number;
  y: number;
}
export interface Bezier {
  c1: Point;
  c2: Point;
}
export interface ObjectState {
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  opacity: number;
  visible: boolean;
  fill: string;
  stroke: string;
  strokeWidth: number;
  text: string;
  fontSize: number;
  cornerRadius: number;
  effect: Effect;
  path: Bezier;
}
export interface ImageAsset {
  src: string;
  width: number;
  height: number;
}
export interface MediaAsset {
  src: string;
  mime: string;
  duration: number;
  width?: number;
  height?: number;
  hasAudio: boolean;
  waveform?: number[];
}
export interface MediaPlayback {
  start: number;
  offset: number;
  duration: number;
}
export interface SceneObject {
  id: string;
  name: string;
  kind: ObjectKind;
  order: number;
  groupId: string | null;
  locked: boolean;
  image?: ImageAsset;
  media?: MediaAsset;
  playback?: MediaPlayback;
}
export interface Composition {
  id: string;
  name: string;
  duration: number;
  accent: string;
  states: Record<string, ObjectState>;
  deleted?: boolean;
  incomingTransitionId?: string;
}
export interface AnimationTiming {
  start: number;
  duration: number;
  easing: Easing;
}
export interface AnimationTrack {
  implicit?: boolean;
  objectId: string;
  type: AnimationKind;
  start: number;
  duration: number;
  easing: Easing;
  order: 'together' | 'sequential';
  path: Bezier | null;
  positionTiming?: AnimationTiming | null;
  opacityTiming?: AnimationTiming | null;
  sizeTiming?: AnimationTiming | null;
  rotationTiming?: AnimationTiming | null;
  fillTiming?: AnimationTiming | null;
  strokeTiming?: AnimationTiming | null;
  strokeWidthTiming?: AnimationTiming | null;
  fontSizeTiming?: AnimationTiming | null;
  cornerRadiusTiming?: AnimationTiming | null;
  pathTiming?: AnimationTiming | null;
  revealTiming?: AnimationTiming | null;
}
export interface Transition {
  id: string;
  fromId: string;
  toId: string;
  duration: number;
  tracks: Record<string, AnimationTrack>;
}
export interface AudioTrack {
  id: string;
  name: string;
  asset: MediaAsset;
  volume: number;
  muted: boolean;
  start: number;
  offset: number;
  duration: number;
}
export interface Scene {
  id: string;
  name: string;
  width: number;
  height: number;
  background: string;
  objects: Record<string, SceneObject>;
  compositionOrder: string[];
  compositions: Record<string, Composition>;
  transitions: Record<string, Transition>;
  audioTracks?: Record<string, AudioTrack>;
  deleted?: boolean;
}
export interface Project {
  version: 1;
  name: string;
  sceneOrder: string[];
  scenes: Record<string, Scene>;
}
export interface Segment {
  kind: 'composition' | 'transition';
  id: string;
  start: number;
  duration: number;
}
export interface RenderObject {
  object: SceneObject;
  state: ObjectState;
  writeProgress: number;
  order: 'together' | 'sequential';
  videoTimeMs?: number;
  videoFrame?: string; // Portable SVG preparation only; not stored in a project.
}
export interface Frame {
  objects: RenderObject[];
  background: string;
  width: number;
  height: number;
}
