// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { sceneStructureView, projectStructureView } from "../../../_build/js/release/build/boundary/boundary.js";
