// The browser links these packages together once. Other hosts keep their own
// entry points; export/file I/O, codecs and the public site remain lazy/separate.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const workspace = fileURLToPath(new URL('../', import.meta.url));
export const clientPackages = ['boundary', 'browser_editor', 'browser_media', 'browser_render', 'browser_undo', 'ui'];

export function readClientExports(root = workspace) {
  return new Map(clientPackages.map(name => {
    const path = join(root, 'moonbit', name, 'moon.pkg');
    const section = readFileSync(path, 'utf8').match(/"exports":\s*\[([^\]]*)\]/)?.[1];
    if (!section) throw new Error(`Missing JS exports in ${path}`);
    const names = new Set();
    const entries = JSON.parse(`[${section.replace(/,\s*$/, '')}]`).map(binding => {
      if (typeof binding !== 'string' || !/^[A-Za-z_]\w*(?::[A-Za-z_]\w*)?$/.test(binding)) {
        throw new Error(`Unsupported JS export ${JSON.stringify(binding)} in ${path}`);
      }
      const [local, exported = local] = binding.split(':');
      if (names.has(exported)) throw new Error(`Duplicate JS export ${exported} in ${path}`);
      names.add(exported);
      return { local, exported };
    });
    return [name, entries];
  }));
}

export function generateClientRuntime(root = workspace) {
  const packages = readClientExports(root);
  const header = '// Generated by scripts/client-runtime.mjs from package JS exports; do not edit.\n';
  const source = [...packages].map(([name, entries]) => `
///|
#export_name("${name}")
pub fn export_${name}() -> @core.Any {
  @core.from_entries([
${entries.map(({ local, exported }) => {
    // MoonBit cannot take a function value with labelled parameters. Keep the
    // original foreign ABI for this one entry in adapters.mbt.
    const fn = name === 'ui' && local === 'use_prepared_stage_frame' ? 'prepared_stage_frame' : `@${name}.${local}`;
    return `    ("${exported}", @core.any(${fn})),`;
  }).join('\n')}
  ])
}
`).join('');
  const directory = join(root, 'moonbit/client_runtime');
  mkdirSync(directory, { recursive: true });
  writeFileSync(join(directory, 'exports.mbt'), header + source);
  writeFileSync(join(directory, 'moon.pkg'), header + `import {
  "mizchi/js_core" @core,
${clientPackages.map(name => `  "poietra/poietra/${name}",`).join('\n')}
}

supported_targets = "js"

pkgtype(kind: "foreign_library")

options(link: { "js": { "format": "esm" } })
`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) generateClientRuntime();
