"""Generate representation-only JS adapters from the typed MoonBit document.

No JSON serialization per frame: image/video data URLs remain shared strings.
Domain behavior stays in moonbit/scene. This emitter intentionally handles only
the field types used by that package and fails for an unknown representation.
"""
from pathlib import Path
import re
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
args = parser.parse_args()

root = args.root
model = (root / 'moonbit/scene/model.mbt').read_text()
structs = {}
for name, body in re.findall(r'pub\(all\) struct (\w+)\s*\{([^}]+)\}', model):
    fields = []
    for line in re.split(r'[;\n]', body):
        line = re.sub(r'//.*', '', line).strip()
        if not line:
            continue
        field, kind = re.split(r'\s*:\s*', line, maxsplit=1)
        fields.append((field, kind))
    structs[name] = fields

def decode(kind, value):
    if kind.endswith('?'):
        return f'optional({value}, fn(v) {{ {decode(kind[:-1], "v")} }})'
    if kind in ['Double', 'Int', 'String', 'Bool']:
        return f'{value}.cast()'
    if kind.startswith('Array['):
        return f'decode_array({value}, fn(v) {{ {decode(kind[6:-1], "v")} }})'
    if kind.startswith('Map[String, '):
        return f'decode_map({value}, fn(v) {{ {decode(kind[12:-1], "v")} }})'
    if kind in ['Easing', 'ObjectKind', 'AnimationKind', 'Effect'] or kind in structs:
        return f'decode_{kind}({value})'
    raise ValueError(kind)

def encode_value(kind, expression):
    if kind.endswith('?'):
        return f'match {expression} {{ Some(item) => {encode_value(kind[:-1], "item")}; None => @core.undefined() }}'
    if kind in ['Double', 'Int', 'String', 'Bool']:
        return f'@core.any({expression})'
    if kind == 'ObjectKind':
        return f'@core.any(@scene.object_kind_name({expression}))'
    if kind in ['Effect', 'AnimationKind']:
        name = 'effect_name' if kind == 'Effect' else 'animation_name'
        return f'@core.any(@scene.{name}({expression}))'
    if kind == 'Easing':
        return f'encode_Easing({expression})'
    if kind.startswith('Array['):
        return f'encode_array({expression}, fn(item) {{ {encode_value(kind[6:-1], "item")} }})'
    if kind.startswith('Map[String, '):
        return f'encode_map({expression}, fn(item) {{ {encode_value(kind[12:-1], "item")} }})'
    if kind in structs:
        return f'encode_{kind}({expression})'
    raise ValueError(kind)


source = '''// Generated by scripts/generate-adapters.py. Representation only.
///|
fn[T] optional(value : @core.Any, decode : (@core.Any) -> T) -> T? {
  if @core.is_nullish(value) { None } else { Some(decode(value)) }
}
///|
fn[T] decode_array(value : @core.Any, decode : (@core.Any) -> T) -> Array[T] {
  let items : FixedArray[@core.Any] = value.cast()
  Array::makei(items.length(), fn(i) { decode(items[i]) })
}
///|
fn[T] decode_map(value : @core.Any, decode : (@core.Any) -> T) -> Map[String, T] {
  let result = Map([])
  for key in @core.object_keys(value) { result[key] = decode(value._get(key)) }
  result
}
///|
fn decode_Easing(value : @core.Any) -> @scene.Easing {
  if @core.typeof_(value) == "string" {
    let name : String = value.cast()
    match name {
      "easeInOut" => @scene.EaseInOut
      "easeIn" => @scene.EaseIn
      "easeOut" => @scene.EaseOut
      _ => @scene.Linear
    }
  } else {
    @scene.CubicBezier(value._get("x1").cast(), value._get("y1").cast(), value._get("x2").cast(), value._get("y2").cast())
  }
}
'''
for name, parser in [('ObjectKind', 'object_kind'), ('AnimationKind', 'animation_kind'), ('Effect', 'effect_kind')]:
    source += f'''///|
fn decode_{name}(value : @core.Any) -> @scene.{name} {{
  if @core.typeof_(value) != "string" {{ @core.throw_error("Expected {name} string"); panic() }}
  match @scene.{parser}(value.cast()) {{
    Some(kind) => kind
    None => {{ @core.throw_error("Invalid {name}"); panic() }}
  }}
}}
'''
for name, fields in structs.items():
    if name in ['RenderObject', 'Frame', 'Segment', 'Project']:
        continue
    source += f'///|\nfn decode_{name}(value : @core.Any) -> @scene.{name} {{\n  {{\n'
    for field, kind in fields:
        key = 'type' if field == 'type_' else field
        source += f'    {field}: {decode(kind, f"value._get(\"{key}\")")},\n'
    source += '  }\n}\n'
for name in ['Point', 'Bezier', 'ObjectState']:
    fields = structs[name]
    arguments = ', '.join(f'{field} : {"String" if kind == "Effect" else kind if kind in ["Double", "Int", "String", "Bool"] else "@core.Any"}' for field, kind in fields)
    keys = ', '.join(field for field, _ in fields)
    source += f'///|\nextern "js" fn make_{name}({arguments}) -> @core.Any =\n  #|({keys}) => ({{{keys}}})\n'
    source += f'///|\nfn encode_{name}(value : @scene.{name}) -> @core.Any {{\n  make_{name}(\n'
    for field, kind in fields:
        expression = f'@scene.effect_name(value.{field})' if kind == 'Effect' else f'value.{field}' if kind in ['Double', 'Int', 'String', 'Bool'] else encode_value(kind, f'value.{field}')
        source += f'    {expression},\n'
    source += '  )\n}\n'
# Additional sparse records use the same canonical model fields.
source += '\n'+"""///|
extern "js" fn make_curve(x1 : Double, y1 : Double, x2 : Double, y2 : Double) -> @core.Any =
  #|(x1, y1, x2, y2) => ({type: 'cubicBezier', x1, y1, x2, y2})
///|
fn encode_Easing(value : @scene.Easing) -> @core.Any {
  match value {
    Linear => @core.any("linear")
    EaseInOut => @core.any("easeInOut")
    EaseIn => @core.any("easeIn")
    EaseOut => @core.any("easeOut")
    CubicBezier(x1, y1, x2, y2) => make_curve(x1, y1, x2, y2)
  }
}
///|
fn encode_Timing(value : @scene.Timing) -> @core.Any {
  make_timing(@core.any(value.start), @core.any(value.duration), encode_Easing(value.easing))
}
///|
extern "js" fn make_track(object_id : String, kind : String, start : Double, duration : Double, easing : @core.Any, order : String, path : @core.Any) -> @core.Any =
  #|(objectId, type, start, duration, easing, order, path) => ({objectId, type, start, duration, easing, order, path})
///|
fn encode_Track(value : @scene.Track) -> @core.Any {
  let path = match value.path { Some(path) => encode_Bezier(path); None => @core.null() }
  let result = make_track(value.objectId, @scene.animation_name(value.type_), value.start, value.duration, encode_Easing(value.easing), value.order, path)
"""
for field, kind in structs['Track']:
    if not kind.endswith('?') or field == 'path':
        continue
    expression = '@core.any(item)' if kind == 'Bool?' else f'encode_{kind[:-1]}(item)'
    source += f'  if value.{field} is Some(item) {{ put_own(result, "{field}", {expression}) }}\n'
source += '  result\n}\n'

# Document copies use direct adapters too, so inline media is never stringified.

source += """///|
fn[T] encode_array(value : Array[T], convert : (T) -> @core.Any) -> @core.Any {
  @core.any(FixedArray::makei(value.length(), fn(i) { convert(value[i]) }))
}
///|
fn[T] encode_map(value : Map[String, T], convert : (T) -> @core.Any) -> @core.Any {
  let result = @core.new_object()
  for key, item in value { put_own(result, key, convert(item)) }
  result
}
"""
for name in structs:
    if name in ['Point', 'Bezier', 'ObjectState', 'Timing', 'Track', 'Project', 'RenderObject', 'Frame', 'Segment']:
        continue
    source += f'///|\nfn encode_{name}(value : @scene.{name}) -> @core.Any {{\n  let result = @core.new_object()\n'
    for field, kind in structs[name]:
        if kind.endswith('?'):
            source += f'  if value.{field} is Some(item) {{ put_own(result, "{field}", {encode_value(kind[:-1], "item")}) }}'
            if field == 'groupId':
                source += ' else { put_own(result, "groupId", @core.null()) }'
            source += '\n'
        else:
            source += f'  put_own(result, "{field}", {encode_value(kind, f"value.{field}")})\n'
    source += '  result\n}\n'

# Generate the public document representation from the same fields as the codec.
# Overrides describe existing JS wire contracts, not a second domain model.
aliases = {'Timing': 'AnimationTiming', 'Track': 'AnimationTrack'}
def ts_type(kind):
    if kind in ['Double', 'Int']: return 'number'
    if kind == 'String': return 'string'
    if kind == 'Bool': return 'boolean'
    if kind.startswith('Array['): return ts_type(kind[6:-1]) + '[]'
    if kind.startswith('Map[String, '): return 'Record<string, ' + ts_type(kind[12:-1]) + '>'
    if kind in structs or kind in ['ObjectKind', 'AnimationKind', 'Effect', 'Easing']:
        return aliases.get(kind, kind)
    raise ValueError('Unsupported public representation: ' + kind)

kinds = (root / 'moonbit/scene/kinds.mbt').read_text()
def names(function):
    body = re.search(r'pub fn ' + function + r'\(.*?\n}', kinds, re.S).group()
    return re.findall(r'=> "([^"\n]+)"', body)
types = '// Generated by scripts/generate-adapters.py from moonbit/scene/model.mbt and kinds.mbt.\n'
for name, function in [('ObjectKind', 'object_kind_name'), ('AnimationKind', 'animation_name'), ('Effect', 'effect_name')]:
    types += 'export type ' + name + ' = ' + ' | '.join(repr(x) for x in names(function)) + ';\n'
easing = re.findall(r'    (?:Linear|EaseInOut|EaseIn|EaseOut) => "([^"\n]+)"', model)
types += "export type PresetEasing = " + ' | '.join(repr(x) for x in easing) + ';\n'
types += "export interface CubicBezierEasing { type: 'cubicBezier'; x1: number; y1: number; x2: number; y2: number }\n"
types += 'export type Easing = PresetEasing | CubicBezierEasing;\n'
for name, fields in structs.items():
    types += 'export interface ' + aliases.get(name, name) + ' {\n'
    for field, kind in fields:
        key = 'type' if field == 'type_' else field
        optional = kind.endswith('?')
        value = ts_type(kind[:-1] if optional else kind)
        if (name, field) in [('SceneObject', 'groupId'), ('Track', 'path')]:
            optional = False
            value += ' | null'
        elif name == 'Track' and kind == 'Timing?':
            value += ' | null'
        if field == 'order' and name in ['Track', 'RenderObject']: value = "'together' | 'sequential'"
        if name == 'Project' and field == 'version': value = '1'
        if name == 'Segment' and field == 'kind': value = "'composition' | 'transition'"
        types += '  ' + key + ('?' if optional else '') + ': ' + value + ';\n'
    if name == 'RenderObject': types += '  videoFrame?: string; // Portable SVG preparation only; not stored in a project.\n'
    types += '}\n'
for path, content in [
    (root / 'moonbit/boundary/adapters.mbt', source),
    (root / 'apps/studio/shared/scene-types.d.ts', types),
]:
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
