"""Generate representation-only JS adapters from the typed MoonBit document.

No JSON serialization per frame: image/video data URLs remain shared strings.
Domain behavior stays in moonbit/scene. This emitter intentionally handles only
the field types used by that package and fails for an unknown representation.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
model = (root / 'moonbit/scene/model.mbt').read_text()
structs = {}
for name, body in re.findall(r'pub\(all\) struct (\w+)\s*\{([^}]+)\}', model):
    fields = []
    for line in re.split(r'[;\n]', body):
        if not line.strip():
            continue
        field, kind = line.strip().split(' : ')
        fields.append((field, kind))
    structs[name] = fields

def decode(kind, value):
    if kind.endswith('?'):
        return f'optional({value}, fn(v) {{ {decode(kind[:-1], "v")} }})'
    if kind in ['Double', 'Int', 'String', 'Bool']:
        return f'{value}.cast()'
    if kind.startswith('Array['):
        return f'decode_array({value}, fn(v) {{ {decode(kind[6:-1], "v")} }})'
    if kind.startswith('Map[String, '):
        return f'decode_map({value}, fn(v) {{ {decode(kind[12:-1], "v")} }})'
    if kind in ['Easing', 'ObjectKind', 'AnimationKind', 'Effect'] or kind in structs:
        return f'decode_{kind}({value})'
    raise ValueError(kind)

source = '''// Generated by scripts/generate-adapters.py. Representation only.
///|
fn[T] optional(value : @core.Any, decode : (@core.Any) -> T) -> T? {
  if @core.is_nullish(value) { None } else { Some(decode(value)) }
}
///|
fn[T] decode_array(value : @core.Any, decode : (@core.Any) -> T) -> Array[T] {
  let items : FixedArray[@core.Any] = value.cast()
  Array::makei(items.length(), fn(i) { decode(items[i]) })
}
///|
fn[T] decode_map(value : @core.Any, decode : (@core.Any) -> T) -> Map[String, T] {
  let result = Map([])
  for key in @core.object_keys(value) { result[key] = decode(value._get(key)) }
  result
}
///|
fn decode_Easing(value : @core.Any) -> @scene.Easing {
  if @core.typeof_(value) == "string" {
    let name : String = value.cast()
    match name {
      "easeInOut" => @scene.EaseInOut
      "easeIn" => @scene.EaseIn
      "easeOut" => @scene.EaseOut
      _ => @scene.Linear
    }
  } else {
    @scene.CubicBezier(value._get("x1").cast(), value._get("y1").cast(), value._get("x2").cast(), value._get("y2").cast())
  }
}
'''
for name, parser in [('ObjectKind', 'object_kind'), ('AnimationKind', 'animation_kind'), ('Effect', 'effect_kind')]:
    source += f'''///|
fn decode_{name}(value : @core.Any) -> @scene.{name} {{
  if @core.typeof_(value) != "string" {{ @core.throw_error("Expected {name} string"); panic() }}
  match @scene.{parser}(value.cast()) {{
    Some(kind) => kind
    None => {{ @core.throw_error("Invalid {name}"); panic() }}
  }}
}}
'''
for name, fields in structs.items():
    if name in ['RenderObject', 'Frame', 'Segment', 'Project']:
        continue
    source += f'///|\nfn decode_{name}(value : @core.Any) -> @scene.{name} {{\n  {{\n'
    for field, kind in fields:
        key = 'type' if field == 'type_' else field
        source += f'    {field}: {decode(kind, f"value._get(\"{key}\")")},\n'
    source += '  }\n}\n'
for name in ['Point', 'Bezier', 'ObjectState']:
    fields = structs[name]
    arguments = ', '.join(f'{field} : {"String" if kind == "Effect" else kind if kind in ["Double", "Int", "String", "Bool"] else "@core.Any"}' for field, kind in fields)
    keys = ', '.join(field for field, _ in fields)
    source += f'///|\nextern "js" fn make_{name}({arguments}) -> @core.Any =\n  #|({keys}) => ({{{keys}}})\n'
    source += f'///|\nfn encode_{name}(value : @scene.{name}) -> @core.Any {{\n  make_{name}(\n'
    for field, kind in fields:
        expression = f'@scene.effect_name(value.{field})' if kind == 'Effect' else f'value.{field}' if kind in ['Double', 'Int', 'String', 'Bool'] else f'encode_{kind}(value.{field})'
        source += f'    {expression},\n'
    source += '  )\n}\n'
(root / 'moonbit/boundary/adapters.mbt').write_text(source)
