import { createElement } from "react";
import { portableProject, rehostImageAssets } from "./editor/images.js";
import { createProjectRoom } from "./editor/projects.js";
import { App as MoonApp } from "../../../_build/js/release/build/ui/ui.js";
import "./ui/AssistantPanel.css";
import "./ui/ConnectionStatus.css";
import "./ui/EasingEditor.css";
import "./ui/export-dialog.css";
import "./ui/groups.css";
import "./ui/MediaTimeline.css";
import "./ui/OperationFeedback.css";
import "./ui/ProjectDialog.css";
import "./ui/ProjectPreview.css";
import "./ui/PropertyAnimation.css";
import "./ui/SceneTabs.css";
import "./ui/Stage.css";
import "./ui/TexInput.css";
import "./ui/TimelineFeedback.css";
import "./ui/TimelineSeek.css";
const services = { portableProject, rehostImageAssets, createProjectRoom };
export const App = props => createElement(MoonApp, { ...props, services });
