// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { isEditorLocation, lastRoom, roomLink } from "../../../_build/js/release/build/site_shell/site_shell.js";
