// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { prepareEquationDrawing } from "../../../../../_build/js/release/build/browser_render/browser_render.js";
