// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { imageBlob, blobDataUrl } from "../../../../../_build/js/release/build/browser_media/browser_media.js";
