// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { svgColor as color, svgEscape as escapeXml, svgFinite as finite, svgUnit as unit, svgNumber as number, svgId as safeId } from "../../../../../_build/js/release/build/boundary/boundary.js";
