// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { assetValue, r2AssetResponse, handleAssetRequest } from "../../../_build/js/release/build/worker_assets/worker_assets.js";
