// Generated by scripts/generate-bindings.mjs; edit scripts/bindings.json and the adjacent public declaration.
export { readPresenceUpdate, presenceMessage } from "../../../_build/js/release/build/server_presence/server_presence.js";
