import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

// Run against a production build: pnpm build:web && PORT=5188 pnpm start
// POIETRA_TEST_URL=http://127.0.0.1:5188 pnpm exec playwright test dogfood-home-seo
test.beforeEach(({}, info) => {
  test.skip(!process.env.POIETRA_TEST_URL && info.config.metadata.production !== true,
    'Prerendered HTML is generated by the production build.');
});

test('English and Japanese product pages remain readable without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, locale: 'en-US' });
  try {
    const page = await context.newPage();
    for (const [path, locale, description] of [['/?lang=en', 'en', 'Your idea.'], ['/ja/', 'ja', 'ひとりのアイデアを、']] as const) {
      const response = await page.goto(path);
      expect(response?.status()).toBe(200);
      await expect(page.locator('html')).toHaveAttribute('lang', locale);
      await expect(page.getByRole('heading', { level: 1 })).toHaveText('Motion,together.');
      await expect(page.locator('.landing-hero-statement')).toContainText(description);
      await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', `https://poietra.com/${locale === 'ja' ? 'ja/' : ''}`);
      const schema = JSON.parse((await page.locator('script[type="application/ld+json"]').textContent())!);
      expect(schema['@type']).toBe('WebApplication'); expect(schema.inLanguage).toBe(locale);
    }
  } finally { await context.close(); }
});

test('crawler endpoints and negotiated Markdown return public content with correct types', async ({ request }) => {
  for (const [path, mime, text] of [['/robots.txt', 'text/plain', 'Sitemap:'], ['/sitemap.xml', 'xml', '<urlset'], ['/llms.txt', 'text/plain', '# Poietra'], ['/index.md', 'text/markdown', '# Poietra']] as const) {
    const response = await request.get(path);
    expect(response.status()).toBe(200); expect(response.headers()['content-type']).toContain(mime);
    expect(await response.text()).toContain(text); expect(await response.text()).not.toContain('<div id="root"');
  }
  const markdown = await request.get('/?lang=ja', { headers: { Accept: 'text/markdown' } });
  expect(markdown.headers()['content-type']).toContain('text/markdown');
  expect(markdown.headers().vary).toContain('Accept');
  expect(await markdown.text()).toContain('友人と、AIと。');
  const html = await request.get('/', { headers: { Accept: 'text/markdown;q=0, text/html' } });
  expect(html.headers()['content-type']).toContain('text/html');
});

test('editor entry HTML is noindex and keeps project URLs out of marketing pages', async ({ request }) => {
  for (const path of ['/studio', '/?room=seo_read_only_probe_001', '/?projects=1']) {
    const response = await request.get(path);
    expect(response.status()).toBe(200);
    expect(response.headers()['x-robots-tag']).toContain('noindex');
    expect(await response.text()).toContain('name="robots" content="noindex');
    expect(await response.text()).not.toContain('id="landing-title"');
  }
  const missing = await request.get('/not-a-poietra-page');
  expect(missing.status()).toBe(404);
});

test('hydration keeps the static page and limits Japanese font requests', async ({ page }) => {
  const errors: string[] = [], fonts: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (/\.woff2?(?:\?|$)/.test(request.url())) fonts.push(request.url()); });
  await page.goto('/ja/?lang=invalid');
  await expect(page.getByRole('button', { name: '新しいプロジェクト', exact: true })).toBeVisible();
  const slider = page.getByRole('slider', { name: '動きのデモの再生位置', exact: true });
  await slider.focus(); await slider.press('End');
  await expect(slider).toHaveValue('2000');
  await page.evaluate(() => document.fonts.ready);
  expect(fonts.length).toBeLessThanOrEqual(4);
  expect(errors).toEqual([]);
});

test('production editor shares one MoonBit runtime and loads codecs only when export opens', async ({ page }) => {
  const manifest = JSON.parse(readFileSync(new URL('../../dist/.vite/manifest.json', import.meta.url), 'utf8')) as Record<string, { file: string }>;
  const files = Object.values(manifest).map(entry => entry.file);
  const runtime = files.find(file => /\/client_runtime-[^/]+\.js$/.test(file))!;
  const exporter = files.find(file => /\/browser_export-[^/]+\.js$/.test(file))!;
  const codecs = Object.entries(manifest).find(([key]) => key.includes('/mediabunny/'))?.[1].file;
  expect(runtime).toBeTruthy(); expect(exporter).toBeTruthy(); expect(codecs).toBeTruthy();
  const requests: string[] = [], errors: string[] = [];
  // Project creation navigates from home to a new document. Count its imports
  // separately from the creator's cached imports on the previous page.
  page.on('framenavigated', frame => { if (frame === page.mainFrame()) requests.length = 0; });
  page.on('request', request => requests.push(new URL(request.url()).pathname));
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?lang=en');
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  await expect(page.getByText('Live', { exact: true })).toBeVisible({ timeout: 15000 });
  await page.waitForLoadState('networkidle');
  expect(requests.filter(path => path === `/${runtime}`)).toHaveLength(1);
  expect(requests).not.toContain(`/${exporter}`);
  expect(requests).not.toContain(`/${codecs}`);
  expect(requests.filter(path => /\/assets\/(?:boundary|browser_(?:editor|media|render|undo)|svg)-[^/]+\.js$/.test(path))).toEqual([]);
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Export video', exact: true })).toBeEnabled({ timeout: 30000 });
  expect(requests).toContain(`/${exporter}`);
  expect(requests).toContain(`/${codecs}`);
  expect(requests.filter(path => path === `/${runtime}`)).toHaveLength(1);
  expect(errors).toEqual([]);
});
