// Every browser spec has one home. scripts/check-test-suites.mjs rejects omissions.
// Rendering pixel matrices and measurements are opt-in; see README.md (Checks).
export const suites = {
  editor: [
    'ai-compositions.spec.ts',
    'ai-create.spec.ts',
    'ai-dogfood.spec.ts',
    'ai-paths.spec.ts',
    'ai.spec.ts',
    'canvas.spec.ts',
    'chat.spec.ts',
    'clipboard.spec.ts',
    'clipping.spec.ts',
    'connection.spec.ts',
    'dogfood-accounts.spec.ts',
    'dogfood-animation-authoring.spec.ts',
    'dogfood-collaboration.spec.ts',
    'dogfood-custom-easing.spec.ts',
    'dogfood-feedback.spec.ts',
    'dogfood-media.spec.ts',
    'dogfood-property-timing.spec.ts',
    'dogfood-workflows.spec.ts',
    'editor.spec.ts',
    'groups.spec.ts',
    'images.spec.ts',
    'ime.spec.ts',
    'keyboard.spec.ts',
    'layers.spec.ts',
    'marquee.spec.ts',
    'motion-template.spec.ts',
    'painter-preview.spec.ts',
    'playback.spec.ts',
    'primitives.spec.ts',
    'projects.spec.ts',
    'scenes.spec.ts',
    'structure.spec.ts',
    'text-editing.spec.ts',
    'timeline.spec.ts',
    'undo-objects.spec.ts',
    'undo-tracks.spec.ts',
  ],
  components: [
    'dogfood-site-lifecycle.spec.ts',
    'export-dialog.spec.ts',
    'project-preview.spec.ts',
  ],
  mediaEditor: [
    'project-playback.spec.ts',
    'media-files.spec.ts',
  ],
  export: [
    'export.spec.ts',
  ],
  audio: [
    'media-export.spec.ts',
  ],
  site: [
    'developer-site.spec.ts',
    'dogfood-home-seo.spec.ts',
    'dogfood-landing-i18n.spec.ts',
    'dogfood-landing.spec.ts',
  ],
  rendering: [
    'effects.spec.ts',
    'effects-write.spec.ts',
    'effects-shape-text.spec.ts',
    'glow-buffer.spec.ts',
  ],
  measurements: [
    'effects-benchmark.spec.ts',
    'effects-write-benchmark.spec.ts',
    'effects-svg-profile.spec.ts',
    'glow-initialization.spec.ts',
  ],
};
